# Generated by Django 3.1.2 on 2021-03-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210316_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.jpeg', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
