# Generated by Django 3.2.5 on 2021-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210316_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_file',
            field=models.FileField(default='Курсовая работа (заочная форма).doc', upload_to='files/'),
        ),
    ]
